import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'EN' | 'GE' | 'RU';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.about': 'About',
    'nav.menu': 'Menu',
    'nav.coffee': 'Coffee',
    'nav.gallery': 'Gallery',
    'nav.visit': 'Visit Us',
    'nav.order': 'Order Now',
    'hero.title1': 'Batumi’s Favorite',
    'hero.title2': 'Dessert Destination',
    'hero.subtitle': 'Delicious cakes, artisan coffee, and unforgettable sweet moments.',
    'hero.viewMenu': 'View Menu',
    'hero.visitUs': 'Visit Us',
    'about.title1': 'Why Everyone',
    'about.title2': 'Loves Dona',
    'about.p1': 'One of the most loved dessert cafés in Batumi, offering a huge variety of cakes and pastries baked fresh daily.',
    'about.p2': 'We believe in affordable prices with generous portions, ensuring every visit is a sweet celebration. Pair our treats with the perfect coffee to match every dessert.',
    'about.p3': 'A must-visit stop for tourists and locals alike.',
    'about.stat1': 'Dessert Varieties',
    'about.stat2': 'Happy Customers',
    'about.stat3': 'Locations in Batumi',
    'menu.title1': 'Signature',
    'menu.title2': 'Desserts',
    'menu.subtitle': 'Handcrafted daily with love and the finest ingredients.',
    'menu.viewFull': 'View Full Menu',
    'coffee.title1': 'Perfect Coffee',
    'coffee.title2': 'With Every Cake',
    'coffee.p1': 'Enjoy espresso, cappuccino, latte and hot chocolate made from high-quality roasted beans. Our baristas craft each cup to perfectly complement our signature desserts.',
    'coffee.explore': 'Explore Coffee Menu',
    'features.title1': 'Why Visit',
    'features.title2': 'Us',
    'features.subtitle': 'More than just a cafe, Dona is an experience.',
    'gallery.title1': 'Follow Us on',
    'gallery.title2': 'Instagram',
    'location.title1': 'Find',
    'location.title2': 'Us',
    'location.subtitle': 'Visit us in Batumi and enjoy your sweet break.',
    'location.directions': 'Get Directions',
    'location.takeaway': 'Order Takeaway',
    'location.branch': 'Main Branch',
    'location.address': '123 Rustaveli Ave, Batumi, Georgia',
    'location.multiple': '* Multiple branches across the city',
    'location.hoursTitle': 'Opening Hours',
    'location.hours': 'Mon - Sun: 08:00 AM - 11:00 PM',
    'location.contact': 'Contact',
    'cta.title1': 'Life is Better',
    'cta.title2': 'With Cake',
    'cta.btn': 'Visit Dona Today',
    'footer.desc': 'Batumi’s favorite dessert destination. Crafting unforgettable sweet moments with artisan coffee and daily fresh pastries.',
    'footer.explore': 'Explore',
    'footer.contact': 'Contact',
    'footer.rights': 'Dona Bakeshop & Cafe. All rights reserved.',
    'footer.email': 'hello@donacafe.ge',
    'footer.open': 'Open Daily: 08:00 - 23:00',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'modal.close': 'Close',
    'modal.title': 'Full Menu',
    'modal.comingSoon': 'Full digital menu is coming soon! Please visit us in-store to see our daily fresh selection.',
    'features.f1.title': 'Affordable Prices',
    'features.f1.desc': 'Premium quality without the premium price tag.',
    'features.f2.title': 'Huge Variety',
    'features.f2.desc': 'Over 100 different cakes, pastries, and desserts.',
    'features.f3.title': 'Generous Portions',
    'features.f3.desc': 'Slices big enough to share, but too good to.',
    'features.f4.title': 'Fresh Daily',
    'features.f4.desc': 'Baked fresh every morning by our expert pastry chefs.',
    'features.f5.title': 'Cozy Atmosphere',
    'features.f5.desc': 'A warm, inviting space perfect for relaxing.',
    'features.f6.title': 'Tourist Favorite',
    'features.f6.desc': 'A must-visit destination for anyone in Batumi.',
    'gallery.view': 'View',
    'testimonials.role': 'Google Review',
    'testimonials.t1.text': "The Napoleon cake here is legendary! Huge portions and very affordable prices. Always a must-visit in Batumi.",
    'testimonials.t1.author': "Anna S.",
    'testimonials.t2.text': "Very tasty pastries and cakes. The place is usually crowded, which speaks for its popularity. Great coffee too!",
    'testimonials.t2.author': "Mikhail V.",
    'testimonials.t3.text': "საუკეთესო ტორტები ბათუმში! (Best cakes in Batumi!) Always fresh and delicious. I recommend the Red Velvet.",
    'testimonials.t3.author': "Giorgi M.",
    'testimonials.t4.text': "Huge variety of sweets. You can't just choose one. The prices are surprisingly low for such high quality.",
    'testimonials.t4.author': "Elena K.",
    'testimonials.t5.text': "A paradise for sweet tooths. The pistachio eclairs are my absolute favorites. Will definitely come back.",
    'testimonials.t5.author': "Sophie T.",
    'desserts.d1.name': 'Red Velvet Cake',
    'desserts.d1.desc': 'Classic layers with cream cheese frosting.',
    'desserts.d2.name': 'Napoleon Cake',
    'desserts.d2.desc': 'Flaky puff pastry with rich vanilla custard.',
    'desserts.d3.name': 'Berry Cheesecake',
    'desserts.d3.desc': 'Creamy cheesecake topped with fresh berries.',
    'desserts.d4.name': 'Pistachio Eclair',
    'desserts.d4.desc': 'Choux pastry filled with pistachio cream.',
    'desserts.d5.name': 'Pavlova',
    'desserts.d5.desc': 'Crispy meringue with whipped cream and fruit.',
    'desserts.d6.name': 'Carrot Cake',
    'desserts.d6.desc': 'Moist spiced cake with walnuts and frosting.',
    'desserts.d7.name': 'Macarons',
    'desserts.d7.desc': 'Assorted delicate French almond cookies.',
    'desserts.d8.name': 'Pancake Cake',
    'desserts.d8.desc': 'Layers of thin crepes with sweet cream.',
    'coffee.c1.name': 'Espresso',
    'coffee.c2.name': 'Cappuccino',
    'coffee.c3.name': 'Latte',
    'coffee.c4.name': 'Hot Chocolate',
  },
  GE: {
    'nav.about': 'ჩვენს შესახებ',
    'nav.menu': 'მენიუ',
    'nav.coffee': 'ყავა',
    'nav.gallery': 'გალერეა',
    'nav.visit': 'გვეწვიეთ',
    'nav.order': 'შეკვეთა',
    'hero.title1': 'ბათუმის საყვარელი',
    'hero.title2': 'სადესერტო ადგილი',
    'hero.subtitle': 'უგემრიელესი ტორტები, არტიზანული ყავა და დაუვიწყარი ტკბილი წუთები.',
    'hero.viewMenu': 'მენიუს ნახვა',
    'hero.visitUs': 'გვეწვიეთ',
    'about.title1': 'რატომ უყვართ',
    'about.title2': 'დონა',
    'about.p1': 'ერთ-ერთი ყველაზე საყვარელი სადესერტო კაფე ბათუმში, რომელიც გთავაზობთ ყოველდღიურად გამომცხვარი ტორტებისა და ნამცხვრების უდიდეს არჩევანს.',
    'about.p2': 'ჩვენ გვჯერა ხელმისაწვდომი ფასების და დიდი ულუფების. შეუხამეთ ჩვენი ტკბილეული იდეალურ ყავას.',
    'about.p3': 'აუცილებლად სანახავი ადგილი ტურისტებისა და ადგილობრივებისთვის.',
    'about.stat1': 'სახეობის დესერტი',
    'about.stat2': 'კმაყოფილი მომხმარებელი',
    'about.stat3': 'ფილიალი ბათუმში',
    'menu.title1': 'საფირმო',
    'menu.title2': 'დესერტები',
    'menu.subtitle': 'მზადდება ყოველდღიურად სიყვარულით და საუკეთესო ინგრედიენტებით.',
    'menu.viewFull': 'სრული მენიუს ნახვა',
    'coffee.title1': 'იდეალური ყავა',
    'coffee.title2': 'ყველა ნამცხვართან',
    'coffee.p1': 'მიირთვით ესპრესო, კაპუჩინო, ლატე და ცხელი შოკოლადი, დამზადებული უმაღლესი ხარისხის მოხალული მარცვლებისგან.',
    'coffee.explore': 'ყავის მენიუ',
    'features.title1': 'რატომ უნდა',
    'features.title2': 'გვესტუმროთ',
    'features.subtitle': 'დონა უფრო მეტია, ვიდრე უბრალოდ კაფე.',
    'gallery.title1': 'გამოგვყევით',
    'gallery.title2': 'ინსტაგრამზე',
    'location.title1': 'გვიპოვეთ',
    'location.title2': 'აქ',
    'location.subtitle': 'გვესტუმრეთ ბათუმში და ისიამოვნეთ ტკბილი შესვენებით.',
    'location.directions': 'მიმართულება',
    'location.takeaway': 'გატანით შეკვეთა',
    'location.branch': 'მთავარი ფილიალი',
    'location.address': 'რუსთაველის გამზ. 123, ბათუმი, საქართველო',
    'location.multiple': '* რამდენიმე ფილიალი ქალაქის მასშტაბით',
    'location.hoursTitle': 'სამუშაო საათები',
    'location.hours': 'ორშ - კვი: 08:00 - 23:00',
    'location.contact': 'კონტაქტი',
    'cta.title1': 'ცხოვრება უკეთესია',
    'cta.title2': 'ტორტთან ერთად',
    'cta.btn': 'გვესტუმრეთ დღესვე',
    'footer.desc': 'ბათუმის საყვარელი სადესერტო ადგილი. დაუვიწყარი ტკბილი წუთები არტიზანულ ყავასთან ერთად.',
    'footer.explore': 'ნავიგაცია',
    'footer.contact': 'კონტაქტი',
    'footer.rights': 'დონა. ყველა უფლება დაცულია.',
    'footer.email': 'hello@donacafe.ge',
    'footer.open': 'ყოველდღე: 08:00 - 23:00',
    'footer.privacy': 'კონფიდენციალურობის პოლიტიკა',
    'footer.terms': 'მომსახურების პირობები',
    'modal.close': 'დახურვა',
    'modal.title': 'სრული მენიუ',
    'modal.comingSoon': 'სრული ციფრული მენიუ მალე დაემატება! გვეწვიეთ ადგილზე ყოველდღიური არჩევანის სანახავად.',
    'features.f1.title': 'ხელმისაწვდომი ფასები',
    'features.f1.desc': 'პრემიუმ ხარისხი პრემიუმ ფასის გარეშე.',
    'features.f2.title': 'დიდი არჩევანი',
    'features.f2.desc': '100-ზე მეტი სხვადასხვა ტორტი, ნამცხვარი და დესერტი.',
    'features.f3.title': 'დიდი ულუფები',
    'features.f3.desc': 'საკმარისად დიდი გასაზიარებლად, მაგრამ ზედმეტად გემრიელი საამისოდ.',
    'features.f4.title': 'ყოველდღიურად ახალი',
    'features.f4.desc': 'ცხვება ყოველ დილით ჩვენი ექსპერტი კონდიტრების მიერ.',
    'features.f5.title': 'მყუდრო გარემო',
    'features.f5.desc': 'თბილი, მიმზიდველი სივრცე, იდეალური დასვენებისთვის.',
    'features.f6.title': 'ტურისტების ფავორიტი',
    'features.f6.desc': 'აუცილებლად სანახავი ადგილი ბათუმში.',
    'gallery.view': 'ნახვა',
    'testimonials.role': 'Google-ის შეფასება',
    'testimonials.t1.text': "ნაპოლეონის ტორტი აქ ლეგენდარულია! დიდი ულუფები და ძალიან ხელმისაწვდომი ფასები. აუცილებლად უნდა ეწვიოთ ბათუმში.",
    'testimonials.t1.author': "ანა ს.",
    'testimonials.t2.text': "ძალიან გემრიელი ნამცხვრები და ტორტები. ადგილი ჩვეულებრივ ხალხმრავალია, რაც მის პოპულარობაზე მეტყველებს. ყავაც შესანიშნავია!",
    'testimonials.t2.author': "მიხეილ ვ.",
    'testimonials.t3.text': "საუკეთესო ტორტები ბათუმში! ყოველთვის ახალი და გემრიელი. გირჩევთ წითელ ხავერდს.",
    'testimonials.t3.author': "გიორგი მ.",
    'testimonials.t4.text': "ტკბილეულის უზარმაზარი არჩევანი. მხოლოდ ერთს ვერ აირჩევთ. ფასები გასაოცრად დაბალია ასეთი მაღალი ხარისხისთვის.",
    'testimonials.t4.author': "ელენა კ.",
    'testimonials.t5.text': "სამოთხე ტკბილეულის მოყვარულთათვის. ფისტას ეკლერები ჩემი აბსოლუტური ფავორიტია. აუცილებლად დავბრუნდები.",
    'testimonials.t5.author': "სოფიო ტ.",
    'desserts.d1.name': 'წითელი ხავერდი',
    'desserts.d1.desc': 'კლასიკური ფენები ნაღების ყველის კრემით.',
    'desserts.d2.name': 'ნაპოლეონი',
    'desserts.d2.desc': 'ფენოვანი ცომი მდიდარი ვანილის კრემით.',
    'desserts.d3.name': 'კენკრის ჩიზქეიქი',
    'desserts.d3.desc': 'კრემოვანი ჩიზქეიქი ახალი კენკრით.',
    'desserts.d4.name': 'ფისტას ეკლერი',
    'desserts.d4.desc': 'შუ ფისტას კრემით.',
    'desserts.d5.name': 'პავლოვა',
    'desserts.d5.desc': 'ხრაშუნა ბეზე ათქვეფილი ნაღებით და ხილით.',
    'desserts.d6.name': 'სტაფილოს ტორტი',
    'desserts.d6.desc': 'ნოტიო სურნელოვანი ტორტი ნიგვზით და კრემით.',
    'desserts.d7.name': 'მაკარუნი',
    'desserts.d7.desc': 'ნაზი ფრანგული ნუშის ორცხობილა.',
    'desserts.d8.name': 'ბლინების ტორტი',
    'desserts.d8.desc': 'თხელი ბლინების ფენები ტკბილი კრემით.',
    'coffee.c1.name': 'ესპრესო',
    'coffee.c2.name': 'კაპუჩინო',
    'coffee.c3.name': 'ლატე',
    'coffee.c4.name': 'ცხელი შოკოლადი',
  },
  RU: {
    'nav.about': 'О нас',
    'nav.menu': 'Меню',
    'nav.coffee': 'Кофе',
    'nav.gallery': 'Галерея',
    'nav.visit': 'Посетить',
    'nav.order': 'Заказать',
    'hero.title1': 'Любимое место',
    'hero.title2': 'десертов в Батуми',
    'hero.subtitle': 'Вкусные торты, ремесленный кофе и незабываемые сладкие моменты.',
    'hero.viewMenu': 'Смотреть меню',
    'hero.visitUs': 'Посетите нас',
    'about.title1': 'Почему все',
    'about.title2': 'любят Dona',
    'about.p1': 'Одно из самых любимых десертных кафе в Батуми, предлагающее огромный выбор свежей выпечки.',
    'about.p2': 'Мы верим в доступные цены и щедрые порции. Сочетайте наши десерты с идеальным кофе.',
    'about.p3': 'Обязательное место для посещения туристами и местными жителями.',
    'about.stat1': 'Видов десертов',
    'about.stat2': 'Довольных клиентов',
    'about.stat3': 'Филиала в Батуми',
    'menu.title1': 'Фирменные',
    'menu.title2': 'Десерты',
    'menu.subtitle': 'Готовятся ежедневно с любовью из лучших ингредиентов.',
    'menu.viewFull': 'Смотреть полное меню',
    'coffee.title1': 'Идеальный кофе',
    'coffee.title2': 'К каждому торту',
    'coffee.p1': 'Наслаждайтесь эспрессо, капучино, латте и горячим шоколадом из высококачественных зерен.',
    'coffee.explore': 'Кофейное меню',
    'features.title1': 'Почему стоит',
    'features.title2': 'посетить нас',
    'features.subtitle': 'Dona — это больше, чем просто кафе.',
    'gallery.title1': 'Следите за нами в',
    'gallery.title2': 'Instagram',
    'location.title1': 'Найдите',
    'location.title2': 'Нас',
    'location.subtitle': 'Посетите нас в Батуми и насладитесь сладким перерывом.',
    'location.directions': 'Маршрут',
    'location.takeaway': 'Заказать с собой',
    'location.branch': 'Главный филиал',
    'location.address': 'пр. Руставели 123, Батуми, Грузия',
    'location.multiple': '* Несколько филиалов по всему городу',
    'location.hoursTitle': 'Часы работы',
    'location.hours': 'Пн - Вс: 08:00 - 23:00',
    'location.contact': 'Контакты',
    'cta.title1': 'Жизнь лучше',
    'cta.title2': 'с тортом',
    'cta.btn': 'Посетите Dona сегодня',
    'footer.desc': 'Любимое место десертов в Батуми. Создаем незабываемые сладкие моменты.',
    'footer.explore': 'Навигация',
    'footer.contact': 'Контакты',
    'footer.rights': 'Dona Bakeshop & Cafe. Все права защищены.',
    'footer.email': 'hello@donacafe.ge',
    'footer.open': 'Ежедневно: 08:00 - 23:00',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия обслуживания',
    'modal.close': 'Закрыть',
    'modal.title': 'Полное меню',
    'modal.comingSoon': 'Полное цифровое меню скоро появится! Посетите нас, чтобы увидеть ежедневный выбор.',
    'features.f1.title': 'Доступные цены',
    'features.f1.desc': 'Премиум качество без премиум ценника.',
    'features.f2.title': 'Огромный выбор',
    'features.f2.desc': 'Более 100 различных тортов, выпечки и десертов.',
    'features.f3.title': 'Щедрые порции',
    'features.f3.desc': 'Достаточно большие, чтобы поделиться, но слишком вкусные для этого.',
    'features.f4.title': 'Свежее каждый день',
    'features.f4.desc': 'Выпекается каждое утро нашими опытными кондитерами.',
    'features.f5.title': 'Уютная атмосфера',
    'features.f5.desc': 'Теплое, привлекательное пространство, идеальное для отдыха.',
    'features.f6.title': 'Любимец туристов',
    'features.f6.desc': 'Обязательное место для посещения в Батуми.',
    'gallery.view': 'Смотреть',
    'testimonials.role': 'Отзыв в Google',
    'testimonials.t1.text': "Торт Наполеон здесь легендарный! Огромные порции и очень доступные цены. Обязательно к посещению в Батуми.",
    'testimonials.t1.author': "Анна С.",
    'testimonials.t2.text': "Очень вкусная выпечка и торты. Место обычно переполнено, что говорит о его популярности. Отличный кофе!",
    'testimonials.t2.author': "Михаил В.",
    'testimonials.t3.text': "Лучшие торты в Батуми! Всегда свежие и вкусные. Рекомендую Красный бархат.",
    'testimonials.t3.author': "Георгий М.",
    'testimonials.t4.text': "Огромный выбор сладостей. Невозможно выбрать что-то одно. Цены удивительно низкие для такого высокого качества.",
    'testimonials.t4.author': "Елена К.",
    'testimonials.t5.text': "Рай для сладкоежек. Фисташковые эклеры - мои абсолютные фавориты. Обязательно вернусь.",
    'testimonials.t5.author': "Софи Т.",
    'desserts.d1.name': 'Красный бархат',
    'desserts.d1.desc': 'Классические слои с крем-чизом.',
    'desserts.d2.name': 'Наполеон',
    'desserts.d2.desc': 'Слоеное тесто с насыщенным ванильным заварным кремом.',
    'desserts.d3.name': 'Ягодный чизкейк',
    'desserts.d3.desc': 'Сливочный чизкейк со свежими ягодами.',
    'desserts.d4.name': 'Фисташковый эклер',
    'desserts.d4.desc': 'Заварное тесто с фисташковым кремом.',
    'desserts.d5.name': 'Павлова',
    'desserts.d5.desc': 'Хрустящее безе со взбитыми сливками и фруктами.',
    'desserts.d6.name': 'Морковный торт',
    'desserts.d6.desc': 'Влажный пряный бисквит с грецкими орехами и кремом.',
    'desserts.d7.name': 'Макарон',
    'desserts.d7.desc': 'Ассорти нежных французских миндальных печений.',
    'desserts.d8.name': 'Блинный торт',
    'desserts.d8.desc': 'Слои тонких блинчиков со сладким кремом.',
    'coffee.c1.name': 'Эспрессо',
    'coffee.c2.name': 'Капучино',
    'coffee.c3.name': 'Латте',
    'coffee.c4.name': 'Горячий шоколад',
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('EN');
  
  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
